#pragma once

#include "pch.h"

#include <glm/glm.hpp>
#include <glm/gtx/quaternion.hpp>

#include "3dspacegame/game_brick_def.h"

/**
 * A celestial object is an instanced object, containing a lot of "bricks" that are generated by the engine, not created by the player
 * 
 */
struct Game_celestial {
    std::vector<Game_brick_instance> _data;

    glm::vec3 pos;
    glm::quat rot;

};